### ISSUE TITLE
Améliorer les configurations

### ISSUE THREAD

**Issue by mathildebrosseau** [mathildebrosseau/transition-python-lib#9]
- [x] Ficher de configuration persistent créé de manière transparente, qui enregistre l'URL prod, URL dev et le username/token de l'utilisateur logging in en dernier
- [x] Quand on ouvre le plugin, demander username, password et URL à utiliser (populer avec valeurs du fichier de config si existants)

**Comment by vincenthaney** [comment]
Demander à Yannick pour la persistance du côté du client
